<a href="https://colab.research.google.com/github/MayankRawat06/NLP-Assignments/blob/main/NLP_in_Python_5_(Topic_Modeling).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Topic Modeling

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## Introduction

Another popular text analysis technique is called topic modeling. The ultimate goal of topic modeling is to find various topics that are present in your corpus. Each document in the corpus will be made up of at least one topic, if not multiple topics.

In this notebook, we will be covering the steps on how to do **Latent Dirichlet Allocation (LDA)**, which is one of many topic modeling techniques. It was specifically designed for text data.

To use a topic modeling technique, you need to provide (1) a document-term matrix and (2) the number of topics you would like the algorithm to pick up.

Once the topic modeling technique is applied, your job as a human is to interpret the results and see if the mix of words in each topic make sense. If they don't make sense, you can try changing up the number of topics, the terms in the document-term matrix, model parameters, or even try a different model.

## Topic Modeling - Attempt #1 (All Text)

In [2]:
# Let's read in our document-term matrix
import pandas as pd
import pickle

data = pd.read_pickle('/content/drive/MyDrive/NLP in Python/pickle/dtm_stop.pkl')
data

,aaaaah,aaaaahhhhhhh,aaaaauuugghhhhhh,aaaahhhhh,aaah,aah,abc,abcs,ability,abject,...,zee,zen,zeppelin,zero,zillion,zombie,zombies,zoning,zoo,éclair
ali,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
anthony,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
bill,1,0,0,0,0,0,0,1,0,0,...,0,0,0,1,1,1,1,1,0,0
bo,0,1,1,1,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
dave,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
hasan,0,0,0,0,0,0,0,0,0,0,...,2,1,0,1,0,0,0,0,0,0
jim,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
joe,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
john,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
louis,0,0,0,0,0,3,0,0,0,0,...,0,0,0,2,0,0,0,0,0,0
mike,0,0,0,0,0,0,0,0,0,0,...,0,0,2,1,0,0,0,0,0,0
ricky,0,0,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,1,0

In [3]:
# Import the necessary modules for LDA with gensim
# Terminal / Anaconda Navigator: conda install -c conda-forge gensim
from gensim import matutils, models
import scipy.sparse

# import logging
# logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)

In [4]:
# One of the required inputs is a term-document matrix
tdm = data.transpose()
tdm.head()

,ali,anthony,bill,bo,dave,hasan,jim,joe,john,louis,mike,ricky
aaaaah,0,0,1,0,0,0,0,0,0,0,0,0
aaaaahhhhhhh,0,0,0,1,0,0,0,0,0,0,0,0
aaaaauuugghhhhhh,0,0,0,1,0,0,0,0,0,0,0,0
aaaahhhhh,0,0,0,1,0,0,0,0,0,0,0,0
aaah,0,0,0,0,1,0,0,0,0,0,0,0

In [5]:
# We're going to put the term-document matrix into a new gensim format, from df --> sparse matrix --> gensim corpus
sparse_counts = scipy.sparse.csr_matrix(tdm)
corpus = matutils.Sparse2Corpus(sparse_counts)

In [7]:
# Gensim also requires dictionary of the all terms and their respective location in the term-document matrix
cv = pickle.load(open("/content/drive/MyDrive/NLP in Python/pickle/cv_stop.pkl", "rb"))
id2word = dict((v, k) for k, v in cv.vocabulary_.items())

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator CountVectorizer from version 0.18.2 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(

Now that we have the corpus (term-document matrix) and id2word (dictionary of location: term), we need to specify two other parameters - the number of topics and the number of passes. Let's start the number of topics at 2, see if the results make sense, and increase the number from there.

In [10]:
# Now that we have the corpus (term-document matrix) and id2word (dictionary of location: term),
# we need to specify two other parameters as well - the number of topics and the number of passes
lda = models.LdaModel(corpus=corpus, id2word=id2word, num_topics=2, passes=10)
lda.print_topics()

[(0,
  '0.005*"say" + 0.005*"hes" + 0.005*"going" + 0.004*"want" + 0.004*"cause" + 0.004*"love" + 0.004*"really" + 0.004*"life" + 0.004*"little" + 0.004*"didnt"'),
 (1,
  '0.012*"fucking" + 0.008*"fuck" + 0.008*"shit" + 0.006*"theyre" + 0.005*"didnt" + 0.005*"going" + 0.005*"say" + 0.005*"man" + 0.005*"thing" + 0.005*"day"')]

In [11]:
# LDA for num_topics = 3
lda = models.LdaModel(corpus=corpus, id2word=id2word, num_topics=3, passes=10)
lda.print_topics()

[(0,
  '0.009*"fucking" + 0.007*"say" + 0.007*"fuck" + 0.006*"theyre" + 0.006*"going" + 0.005*"dad" + 0.004*"want" + 0.004*"shit" + 0.004*"shes" + 0.004*"hes"'),
 (1,
  '0.008*"fucking" + 0.005*"good" + 0.005*"went" + 0.005*"day" + 0.005*"fuck" + 0.005*"say" + 0.005*"shit" + 0.005*"didnt" + 0.004*"going" + 0.004*"man"'),
 (2,
  '0.008*"shit" + 0.006*"cause" + 0.005*"hes" + 0.005*"fucking" + 0.005*"thing" + 0.005*"life" + 0.005*"theres" + 0.005*"theyre" + 0.004*"want" + 0.004*"really"')]

In [12]:
# LDA for num_topics = 4
lda = models.LdaModel(corpus=corpus, id2word=id2word, num_topics=4, passes=10)
lda.print_topics()

[(0,
  '0.010*"fucking" + 0.008*"went" + 0.007*"day" + 0.006*"shit" + 0.006*"fuck" + 0.005*"going" + 0.005*"cause" + 0.005*"women" + 0.005*"theyre" + 0.005*"thing"'),
 (1,
  '0.006*"love" + 0.006*"says" + 0.005*"want" + 0.005*"stuff" + 0.005*"really" + 0.004*"id" + 0.004*"bo" + 0.004*"good" + 0.004*"jenny" + 0.004*"repeat"'),
 (2,
  '0.006*"theyre" + 0.006*"fuck" + 0.006*"cause" + 0.006*"say" + 0.006*"fucking" + 0.006*"shit" + 0.005*"thing" + 0.005*"life" + 0.005*"really" + 0.005*"theres"'),
 (3,
  '0.009*"fucking" + 0.007*"shit" + 0.006*"didnt" + 0.006*"say" + 0.006*"going" + 0.006*"want" + 0.006*"fuck" + 0.005*"hes" + 0.005*"did" + 0.004*"come"')]

These topics aren't looking too great. We've tried modifying our parameters. Let's try modifying our terms list as well.

## Topic Modeling - Attempt #2 (Nouns Only)

One popular trick is to look only at terms that are from one part of speech (only nouns, only adjectives, etc.). Check out the UPenn tag set: https://www.ling.upenn.edu/courses/Fall_2003/ling001/penn_treebank_pos.html.

In [13]:
# Let's create a function to pull out nouns from a string of text
from nltk import word_tokenize, pos_tag

def nouns(text):
    '''Given a string of text, tokenize the text and pull out only the nouns.'''
    is_noun = lambda pos: pos[:2] == 'NN'
    tokenized = word_tokenize(text)
    all_nouns = [word for (word, pos) in pos_tag(tokenized) if is_noun(pos)] 
    return ' '.join(all_nouns)

In [14]:
# Read in the cleaned data, before the CountVectorizer step
data_clean = pd.read_pickle('/content/drive/MyDrive/NLP in Python/pickle/data_clean.pkl')
data_clean

                                                transcript
ali      ladies and gentlemen please welcome to the sta...
anthony  thank you thank you thank you san francisco th...
bill      all right thank you thank you very much thank...
bo       bo what old macdonald had a farm e i e i o and...
dave     this is dave he tells dirty jokes for a living...
hasan      whats up davis whats up im home i had to bri...
jim         ladies and gentlemen please welcome to the ...
joe         ladies and gentlemen welcome joe rogan  wha...
john     all right petunia wish me luck out there you w...
louis    introfade the music out lets roll hold there l...
mike     wow hey thank you thanks thank you guys hey se...
ricky    hello hello how you doing great thank you wow ...

In [16]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [18]:
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.

True

In [19]:
# Apply the nouns function to the transcripts to filter only on nouns
data_nouns = pd.DataFrame(data_clean.transcript.apply(nouns))
data_nouns

                                                transcript
ali      ladies gentlemen stage ali hi thank hello na s...
anthony  thank thank people i em i francisco city world...
bill     thank thank pleasure georgia area oasis i june...
bo       macdonald farm e i o farm pig e i i snort macd...
dave     jokes living stare work profound train thought...
hasan    whats davis whats home i netflix la york i son...
jim      ladies gentlemen stage mr jim jefferies thank ...
joe      ladies gentlemen joe fuck thanks phone fuckfac...
john     petunia thats hello hello chicago thank crowd ...
louis    music lets lights lights thank i i place place...
mike     wow hey thanks look insane years everyone i id...
ricky    hello thank fuck thank im gon youre weve money...

In [20]:
# Create a new document-term matrix using only nouns
from sklearn.feature_extraction import text
from sklearn.feature_extraction.text import CountVectorizer

# Re-add the additional stop words since we are recreating the document-term matrix
add_stop_words = ['like', 'im', 'know', 'just', 'dont', 'thats', 'right', 'people',
                  'youre', 'got', 'gonna', 'time', 'think', 'yeah', 'said']
stop_words = text.ENGLISH_STOP_WORDS.union(add_stop_words)

# Recreate a document-term matrix with only nouns
cvn = CountVectorizer(stop_words=stop_words)
data_cvn = cvn.fit_transform(data_nouns.transcript)
data_dtmn = pd.DataFrame(data_cvn.toarray(), columns=cvn.get_feature_names())
data_dtmn.index = data_nouns.index
data_dtmn

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,aaaaahhhhhhh,aaaaauuugghhhhhh,aaaahhhhh,aah,abc,abcs,ability,abortion,abortions,abuse,...,yummy,ze,zealand,zee,zeppelin,zillion,zombie,zombies,zoo,éclair
ali,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
anthony,0,0,0,0,0,0,0,2,0,0,...,0,0,10,0,0,0,0,0,0,0
bill,0,0,0,0,0,1,0,0,0,0,...,0,1,0,0,0,1,1,1,0,0
bo,1,1,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
dave,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
hasan,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
jim,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
joe,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
john,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
louis,0,0,0,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
mike,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,2,0,0,0,0,0
ricky,0,0,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0

In [21]:
# Create the gensim corpus
corpusn = matutils.Sparse2Corpus(scipy.sparse.csr_matrix(data_dtmn.transpose()))

# Create the vocabulary dictionary
id2wordn = dict((v, k) for k, v in cvn.vocabulary_.items())

In [22]:
# Let's start with 2 topics
ldan = models.LdaModel(corpus=corpusn, num_topics=2, id2word=id2wordn, passes=10)
ldan.print_topics()

[(0,
  '0.007*"way" + 0.006*"thing" + 0.006*"day" + 0.006*"hes" + 0.006*"man" + 0.006*"cause" + 0.006*"years" + 0.005*"night" + 0.005*"id" + 0.005*"things"'),
 (1,
  '0.009*"shit" + 0.009*"day" + 0.009*"life" + 0.009*"thing" + 0.008*"man" + 0.008*"fuck" + 0.007*"hes" + 0.007*"cause" + 0.006*"guy" + 0.006*"lot"')]

In [23]:
# Let's try topics = 3
ldan = models.LdaModel(corpus=corpusn, num_topics=3, id2word=id2wordn, passes=10)
ldan.print_topics()

[(0,
  '0.013*"shit" + 0.010*"man" + 0.009*"fuck" + 0.008*"thing" + 0.008*"hes" + 0.007*"gon" + 0.007*"day" + 0.007*"lot" + 0.006*"life" + 0.006*"dude"'),
 (1,
  '0.008*"day" + 0.007*"joke" + 0.007*"way" + 0.006*"thing" + 0.006*"cause" + 0.006*"stuff" + 0.006*"point" + 0.005*"things" + 0.005*"bo" + 0.005*"school"'),
 (2,
  '0.010*"life" + 0.010*"thing" + 0.010*"day" + 0.008*"dad" + 0.007*"hes" + 0.007*"shes" + 0.007*"cause" + 0.007*"way" + 0.006*"man" + 0.006*"guy"')]

In [24]:
# Let's try 4 topics
ldan = models.LdaModel(corpus=corpusn, num_topics=4, id2word=id2wordn, passes=10)
ldan.print_topics()

[(0,
  '0.009*"day" + 0.008*"cause" + 0.008*"joke" + 0.008*"point" + 0.007*"thing" + 0.007*"school" + 0.007*"way" + 0.006*"kind" + 0.006*"things" + 0.006*"car"'),
 (1,
  '0.013*"shit" + 0.011*"thing" + 0.011*"fuck" + 0.011*"man" + 0.010*"life" + 0.009*"guy" + 0.009*"hes" + 0.009*"cause" + 0.008*"day" + 0.008*"gon"'),
 (2,
  '0.012*"bo" + 0.012*"stuff" + 0.010*"repeat" + 0.009*"eye" + 0.008*"contact" + 0.007*"man" + 0.006*"brain" + 0.006*"cos" + 0.006*"story" + 0.005*"comedy"'),
 (3,
  '0.009*"day" + 0.008*"dad" + 0.007*"hes" + 0.007*"shes" + 0.007*"mom" + 0.007*"years" + 0.006*"life" + 0.006*"thing" + 0.006*"way" + 0.005*"man"')]

## Topic Modeling - Attempt #3 (Nouns and Adjectives)

In [25]:
# Let's create a function to pull out nouns from a string of text
def nouns_adj(text):
    '''Given a string of text, tokenize the text and pull out only the nouns and adjectives.'''
    is_noun_adj = lambda pos: pos[:2] == 'NN' or pos[:2] == 'JJ'
    tokenized = word_tokenize(text)
    nouns_adj = [word for (word, pos) in pos_tag(tokenized) if is_noun_adj(pos)] 
    return ' '.join(nouns_adj)

In [26]:
# Apply the nouns function to the transcripts to filter only on nouns
data_nouns_adj = pd.DataFrame(data_clean.transcript.apply(nouns_adj))
data_nouns_adj

                                                transcript
ali      ladies gentlemen welcome stage ali wong hi wel...
anthony  thank san francisco thank good people surprise...
bill     right thank thank pleasure greater atlanta geo...
bo       old macdonald farm e i i o farm pig e i i snor...
dave     dirty jokes living stare most hard work profou...
hasan    whats davis whats im home i netflix special la...
jim      ladies gentlemen welcome stage mr jim jefferie...
joe      ladies gentlemen joe fuck san francisco thanks...
john     right petunia august thats good right hello he...
louis    music lets lights lights thank much i i i nice...
mike     wow hey thanks hey seattle nice look crazy ins...
ricky    hello great thank fuck thank lovely welcome im...

In [27]:
# Create a new document-term matrix using only nouns and adjectives, also remove common words with max_df
cvna = CountVectorizer(stop_words=stop_words, max_df=.8)
data_cvna = cvna.fit_transform(data_nouns_adj.transcript)
data_dtmna = pd.DataFrame(data_cvna.toarray(), columns=cvna.get_feature_names())
data_dtmna.index = data_nouns_adj.index
data_dtmna

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,aaaaah,aaaaahhhhhhh,aaaaauuugghhhhhh,aaaahhhhh,aah,abc,abcs,ability,abject,able,...,ze,zealand,zee,zeppelin,zero,zillion,zombie,zombies,zoo,éclair
ali,0,0,0,0,0,1,0,0,0,2,...,0,0,0,0,0,0,1,0,0,0
anthony,0,0,0,0,0,0,0,0,0,0,...,0,10,0,0,0,0,0,0,0,0
bill,1,0,0,0,0,0,1,0,0,1,...,1,0,0,0,0,1,1,1,0,0
bo,0,1,1,1,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
dave,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
hasan,0,0,0,0,0,0,0,0,0,1,...,0,0,2,0,0,0,0,0,0,0
jim,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
joe,0,0,0,0,0,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0
john,0,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,1
louis,0,0,0,0,3,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
mike,0,0,0,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,0,0,0
ricky,0,0,0,0,0,0,0,1,1,2,...,0,0,0,0,0,0,0,0,1,0

In [28]:
# Create the gensim corpus
corpusna = matutils.Sparse2Corpus(scipy.sparse.csr_matrix(data_dtmna.transpose()))

# Create the vocabulary dictionary
id2wordna = dict((v, k) for k, v in cvna.vocabulary_.items())

In [29]:
# Let's start with 2 topics
ldana = models.LdaModel(corpus=corpusna, num_topics=2, id2word=id2wordna, passes=10)
ldana.print_topics()

[(0,
  '0.004*"mom" + 0.004*"parents" + 0.003*"joke" + 0.003*"dick" + 0.002*"hasan" + 0.002*"door" + 0.002*"clinton" + 0.002*"wife" + 0.002*"president" + 0.002*"nuts"'),
 (1,
  '0.004*"joke" + 0.003*"friend" + 0.003*"bo" + 0.003*"um" + 0.003*"comedy" + 0.003*"jenny" + 0.003*"ass" + 0.003*"son" + 0.003*"repeat" + 0.003*"guns"')]

In [30]:
# Let's try 3 topics
ldana = models.LdaModel(corpus=corpusna, num_topics=3, id2word=id2wordna, passes=10)
ldana.print_topics()

[(0,
  '0.008*"mom" + 0.005*"parents" + 0.004*"hasan" + 0.004*"clinton" + 0.003*"president" + 0.003*"dick" + 0.003*"door" + 0.003*"husband" + 0.003*"cow" + 0.003*"ass"'),
 (1,
  '0.004*"joke" + 0.003*"jenny" + 0.003*"ahah" + 0.003*"guns" + 0.003*"son" + 0.003*"friend" + 0.003*"class" + 0.003*"ass" + 0.003*"girlfriend" + 0.003*"door"'),
 (2,
  '0.006*"joke" + 0.005*"bo" + 0.004*"repeat" + 0.004*"anthony" + 0.003*"gun" + 0.003*"eye" + 0.003*"comedy" + 0.003*"jokes" + 0.003*"tit" + 0.003*"contact"')]

In [31]:
# Let's try 4 topics
ldana = models.LdaModel(corpus=corpusna, num_topics=4, id2word=id2wordna, passes=10)
ldana.print_topics()

[(0,
  '0.004*"gun" + 0.004*"bo" + 0.003*"dog" + 0.003*"jenny" + 0.003*"guns" + 0.003*"ass" + 0.003*"repeat" + 0.003*"morning" + 0.003*"class" + 0.003*"um"'),
 (1,
  '0.006*"mom" + 0.005*"hasan" + 0.004*"parents" + 0.004*"husband" + 0.003*"door" + 0.003*"ok" + 0.003*"brown" + 0.003*"pregnant" + 0.003*"bike" + 0.003*"ass"'),
 (2,
  '0.000*"joke" + 0.000*"son" + 0.000*"ass" + 0.000*"mom" + 0.000*"guns" + 0.000*"gun" + 0.000*"parents" + 0.000*"jokes" + 0.000*"comedy" + 0.000*"class"'),
 (3,
  '0.009*"joke" + 0.005*"mom" + 0.004*"clinton" + 0.004*"jokes" + 0.004*"ahah" + 0.004*"wife" + 0.003*"mad" + 0.003*"friend" + 0.003*"anthony" + 0.003*"parents"')]

## Identify Topics in Each Document

Out of the 9 topic models we looked at, the nouns and adjectives, 4 topic one made the most sense. So let's pull that down here and run it through some more iterations to get more fine-tuned topics.

In [32]:
# Our final LDA model (for now)
ldana = models.LdaModel(corpus=corpusna, num_topics=4, id2word=id2wordna, passes=80)
ldana.print_topics()

[(0,
  '0.004*"mom" + 0.004*"gun" + 0.004*"ass" + 0.004*"hasan" + 0.004*"guns" + 0.003*"son" + 0.003*"class" + 0.003*"parents" + 0.003*"husband" + 0.003*"brown"'),
 (1,
  '0.006*"joke" + 0.006*"clinton" + 0.005*"mom" + 0.004*"cow" + 0.004*"wife" + 0.004*"nuts" + 0.004*"parents" + 0.003*"jenner" + 0.003*"boy" + 0.003*"hampstead"'),
 (2,
  '0.004*"bo" + 0.004*"jenny" + 0.004*"repeat" + 0.004*"ahah" + 0.004*"friend" + 0.003*"eye" + 0.003*"gay" + 0.003*"contact" + 0.003*"comedy" + 0.003*"door"'),
 (3,
  '0.009*"joke" + 0.007*"anthony" + 0.006*"tit" + 0.005*"grandma" + 0.004*"shark" + 0.004*"mad" + 0.004*"ok" + 0.004*"jokes" + 0.004*"murder" + 0.004*"ha"')]

These four topics look pretty decent. Let's settle on these for now.
* Topic 0: mom, parents
* Topic 1: husband, wife
* Topic 2: guns
* Topic 3: profanity

In [33]:
# Let's take a look at which topics each transcript contains
corpus_transformed = ldana[corpusna]
list(zip([a for [(a,b)] in corpus_transformed], data_dtmna.index))

[(0, 'ali'),
 (3, 'anthony'),
 (0, 'bill'),
 (2, 'bo'),
 (2, 'dave'),
 (0, 'hasan'),
 (0, 'jim'),
 (2, 'joe'),
 (1, 'john'),
 (3, 'louis'),
 (2, 'mike'),
 (1, 'ricky')]

For a first pass of LDA, these kind of make sense to me, so we'll call it a day for now.
* Topic 0: mom, parents [Anthony, Hasan, Louis, Ricky]
* Topic 1: husband, wife [Ali, John, Mike]
* Topic 2: guns [Bill, Bo, Jim]
* Topic 3: profanity [Dave, Joe]

### Assignment:
1. Try further modifying the parameters of the topic models above and see if you can get better topics.
2. Create a new topic model that includes terms from a different [part of speech](https://www.ling.upenn.edu/courses/Fall_2003/ling001/penn_treebank_pos.html) and see if you can get better topics.

In [36]:
# Let's create a function to pull out nouns from a string of text
def nouns_adj_verb(text):
    '''Given a string of text, tokenize the text and pull out only the nouns, adjectives, and verbs.'''
    is_noun_adj_verb = lambda pos: pos[:2] == 'NN' or pos[:2] == 'JJ' or pos[:2] == 'VB'
    tokenized = word_tokenize(text)
    nouns_adj_verb = [word for (word, pos) in pos_tag(tokenized) if is_noun_adj_verb(pos)] 
    return ' '.join(nouns_adj_verb)

In [37]:
# Apply the nouns adj verb function to the transcripts to filter only on nouns verbs and adj
data_nouns_adj_verb = pd.DataFrame(data_clean.transcript.apply(nouns_adj_verb))
data_nouns_adj_verb

                                                transcript
ali      ladies gentlemen please welcome stage ali wong...
anthony  thank thank thank san francisco thank good be ...
bill     right thank thank thank thank are whats going ...
bo       bo old macdonald had farm e i e i o farm had p...
dave     is dave tells dirty jokes living stare is most...
hasan    whats davis whats im home i had bring netflix ...
jim      ladies gentlemen please welcome stage mr jim j...
joe      ladies gentlemen welcome joe rogan fuck is goi...
john     right petunia wish die august thats good right...
louis    introfade music lets roll hold lights do light...
mike     wow hey thank thanks thank guys hey seattle ni...
ricky    hello hello doing great thank wow calm shut fu...

In [39]:
# Create a new document-term matrix using only nouns and adjectives, also remove common words with max_df
cvnav = CountVectorizer(stop_words=stop_words, max_df=.8)
data_cvnav = cvnav.fit_transform(data_nouns_adj.transcript)
data_dtmnav = pd.DataFrame(data_cvnav.toarray(), columns=cvnav.get_feature_names())
data_dtmnav.index = data_nouns_adj_verb.index
data_dtmnav

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,aaaaah,aaaaahhhhhhh,aaaaauuugghhhhhh,aaaahhhhh,aah,abc,abcs,ability,abject,able,...,ze,zealand,zee,zeppelin,zero,zillion,zombie,zombies,zoo,éclair
ali,0,0,0,0,0,1,0,0,0,2,...,0,0,0,0,0,0,1,0,0,0
anthony,0,0,0,0,0,0,0,0,0,0,...,0,10,0,0,0,0,0,0,0,0
bill,1,0,0,0,0,0,1,0,0,1,...,1,0,0,0,0,1,1,1,0,0
bo,0,1,1,1,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
dave,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
hasan,0,0,0,0,0,0,0,0,0,1,...,0,0,2,0,0,0,0,0,0,0
jim,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
joe,0,0,0,0,0,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0
john,0,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,1
louis,0,0,0,0,3,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
mike,0,0,0,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,0,0,0
ricky,0,0,0,0,0,0,0,1,1,2,...,0,0,0,0,0,0,0,0,1,0

In [41]:
# Create the gensim corpus
corpusnav = matutils.Sparse2Corpus(scipy.sparse.csr_matrix(data_dtmnav.transpose()))

# Create the vocabulary dictionary
id2wordnav = dict((v, k) for k, v in cvnav.vocabulary_.items())

In [42]:
# Our final LDA model (for now)
ldanav = models.LdaModel(corpus=corpusnav, num_topics=4, id2word=id2wordnav, passes=80)
ldanav.print_topics()

[(0,
  '0.006*"parents" + 0.005*"hasan" + 0.005*"jenny" + 0.004*"mom" + 0.004*"york" + 0.004*"tit" + 0.003*"date" + 0.003*"brown" + 0.003*"love" + 0.003*"door"'),
 (1,
  '0.006*"clinton" + 0.006*"wife" + 0.005*"mom" + 0.004*"cow" + 0.004*"gun" + 0.004*"parents" + 0.003*"hell" + 0.003*"movie" + 0.003*"jesus" + 0.003*"dick"'),
 (2,
  '0.009*"ahah" + 0.007*"nigga" + 0.006*"gay" + 0.004*"son" + 0.004*"oj" + 0.004*"ghetto" + 0.004*"motherfucker" + 0.004*"young" + 0.004*"kevin" + 0.003*"mad"'),
 (3,
  '0.007*"joke" + 0.004*"jokes" + 0.004*"ass" + 0.003*"bo" + 0.003*"um" + 0.003*"guns" + 0.003*"mom" + 0.003*"eye" + 0.003*"repeat" + 0.003*"party"')]

These four topics look pretty decent. Let's settle on these for now.
* Topic 0: mom, parents, profanity, love, date
* Topic 1: wife, mom, gun, profanity
* Topic 2: lgbt, nigga(community trigger), son, abuse
* Topic 3: profanity, guns, joke, party

In [43]:
# Let's take a look at which topics each transcript contains
corpus_transformed = ldanav[corpusna]
list(zip([a for [(a,b)] in corpus_transformed], data_dtmnav.index))

[(3, 'ali'),
 (3, 'anthony'),
 (1, 'bill'),
 (3, 'bo'),
 (2, 'dave'),
 (0, 'hasan'),
 (3, 'jim'),
 (3, 'joe'),
 (1, 'john'),
 (0, 'louis'),
 (0, 'mike'),
 (3, 'ricky')]

For a second pass of LDA, these kind of make sense to me, so we'll call it a day for now.
* Topic 0: mom, parents, profanity, love, date [hasan, louis, mike]
* Topic 1: wife, mom, gun, profanity [bill, john]
* Topic 2: lgbt, nigga(community trigger), son, abuse [dave]
* Topic 3: profanity, guns, joke, party [ali, anthony, ricky, jim, joe]

In [44]:
# Our final LDA model (for now)
ldanav = models.LdaModel(corpus=corpusnav, num_topics=4, id2word=id2wordnav, passes=100)
ldanav.print_topics()

[(0,
  '0.012*"bo" + 0.010*"repeat" + 0.008*"eye" + 0.008*"contact" + 0.007*"cos" + 0.006*"brain" + 0.006*"um" + 0.005*"sad" + 0.005*"song" + 0.005*"comedy"'),
 (1,
  '0.006*"joke" + 0.004*"friend" + 0.003*"wife" + 0.003*"parents" + 0.003*"mom" + 0.003*"hell" + 0.003*"jenny" + 0.003*"clinton" + 0.003*"mad" + 0.003*"jokes"'),
 (2,
  '0.006*"ok" + 0.004*"husband" + 0.004*"tit" + 0.004*"ass" + 0.003*"dick" + 0.003*"mom" + 0.003*"older" + 0.003*"worst" + 0.003*"pregnant" + 0.003*"date"'),
 (3,
  '0.006*"hasan" + 0.005*"guns" + 0.005*"mom" + 0.004*"class" + 0.004*"parents" + 0.004*"brown" + 0.004*"ass" + 0.004*"son" + 0.004*"girlfriend" + 0.003*"gun"')]